//
//  HomeMapViewModel.swift
//  FoodFinder
//
//  Created by Martin Lukacs on 13/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//

import Combine
import CoreLocation
import Foundation
import MapKit
import Resolver
import SwiftUICombineToolBox

/// Simple page state managment protocol
/// Helps to detemine the view state
enum HomeMapPageState: Equatable {
    case loading
    case localized
}

/// ViewModel in charrge of display iof the mapkit and foursquare data fetching
final class HomeMapViewModel: ObservableObject {
    /// Current user location
    @Published var currentRegion: MKCoordinateRegion!

    /// State of the view
    @Published private(set) var state = HomeMapPageState.loading

    /// <#Description#>
    @Published var displayAlert = false

    /// Venue map Pin annotations
    @Published var mapVenueAnnotations: [MapVenueAnnotation] = []
    private var selectedVenue: MapVenueAnnotation?

    /// Router enabling the detail view nivagation flow
    @Injected var router: RouteToPageContract
    @Injected private var locationRepository: LocationsRepositoryContract
    @Injected private var venueRepository: VenueRepositoryContract

    private var cancelBag = CancelBag()
    private var currentLocation: CLLocationCoordinate2D?

    init() {
        setUp()
    }

    /// Helper function that recenters the map on the current user location
    func resetFocus() {
        guard let currentLocation = currentLocation else {
            return
        }
        currentRegion = createRegion(with: currentLocation)
    }

    /// Set a map annotation to the Current selected venue
    /// - Parameter venue: The mapVune annotation selected by the user
    func setSelectedVenue(for venue: MapVenueAnnotation) {
        selectedVenue = venue
    }

    /// Get id of current Selected venue
    /// - Returns: Return the string id of the current selected venue
    func getSelectedVenueId() -> String {
        selectedVenue?.id ?? ""
    }

    /// Gtter function to accces selected venue
    /// - Returns: The selected venue
    func getSelectedVenue() -> MapVenueAnnotation? {
        selectedVenue
    }

    /// Clean the viewModel selected venue
    func cleanSelection() {
        selectedVenue = nil
    }
}

extension HomeMapViewModel {
    private func setUp() {
        locationRepository.currentLocation
            .compactMap { $0 }
            .flatMap { [weak self] location -> AnyPublisher<[BasicVenue], Never> in
                guard let self = self else {
                    return Just([]).eraseToAnyPublisher()
                }
                self.currentLocation = location
                self.currentRegion = self.createRegion(with: location)
                self.state = .localized
                return self.venueRepository.getRecommended(ofType: BasicVenue.self, for: location, with: APIConfig.baseRadius)
            }
            .receive(on: DispatchQueue.main)
            .sink(receiveValue: { [weak self] venues in
                self?.mapVenueAnnotations = venues.map { VenueFactory.createMapVenueAnnotable(from: $0) }
            })
            .store(in: &cancelBag)

        locationRepository.permissionDenied
            .receive(on: DispatchQueue.main)
            .assignNoRetain(to: \.displayAlert, on: self)
            .store(in: &cancelBag)

        mapPanning
            .compactMap { $0 }
            .flatMap { [weak self] region -> AnyPublisher<[BasicVenue], Never> in
                guard let self = self else {
                    return Just([]).eraseToAnyPublisher()
                }
                return self.venueRepository.getRecommended(ofType: BasicVenue.self,
                                                           for: region.center,
                                                           with: Int(region.distanceMax()))
            }
            .receive(on: DispatchQueue.main)
            .sink(receiveValue: { [weak self] venues in
                self?.updateMapVenueAnnotations(with: venues)
            })
            .store(in: &cancelBag)
    }

    private var mapPanning: AnyPublisher<MKCoordinateRegion?, Never> {
        $currentRegion
            .debounce(for: 0.4, scheduler: RunLoop.main)
            .eraseToAnyPublisher()
    }

    private func createRegion(with location: CLLocationCoordinate2D) -> MKCoordinateRegion {
        .init(center: location,
              latitudinalMeters: GeneralConfiguration.mapLatLongDistance,
              longitudinalMeters: GeneralConfiguration.mapLatLongDistance)
    }

    private func updateMapVenueAnnotations(with venues: [BasicVenueContract]) {
        let newRestaurants = venues.map { VenueFactory.createMapVenueAnnotable(from: $0) }
        var intermediate = mapVenueAnnotations
        intermediate.append(contentsOf: newRestaurants)
        mapVenueAnnotations = Array(Set(intermediate))
    }
}
