//
//  DetailVenuePageView.swift
//  FoodFinder
//
//  Created by Martin Lukacs on 17/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the MVVM Xcode Templates
//

import Kingfisher
import Resolver
import SwiftUI

struct DetailVenuePageView: View {
    @InjectedObject var viewModel: DetailVenuePageViewModel

    var body: some View {
        mainContainer
            .onAppear {
                viewModel.fetchDetailData()
            }
    }
}

extension DetailVenuePageView {
    private var mainContainer: some View {
        Group {
            switch viewModel.state {
            case .loading:
                FoodFinderProgressView()
            case .empty:
                Text("it's a bit empty here")
            case let .detail(venue):
                VStack(alignment: .leading, spacing: 15) {
                    HStack {
                        Spacer()

                        coverImage(for: venue.getBestPhotoUrlString())
                        Spacer()
                    }
                    Text(venue.name)
                        .font(.largeTitle)
                        .fontWeight(.semibold)
                    HStack {
                        Text("Price tier: ")
                        Text("\(venue.price.tier)")
                    }
                    Text("This is the page describing the details of the selected venue")
                    Spacer()
                }.padding(10)
            }
        }
    }
}

// MARK: - Cover Image

extension DetailVenuePageView {
    private func coverImage(for photoUrl: String) -> some View {
        KFImage(URL(string: photoUrl)!)
    }
}

struct DetailVenuePageView_Previews: PreviewProvider {
    static var previews: some View {
        DetailVenuePageView()
    }
}
